### ISSUE TITLE
NullReferenceException when installing Glamourer plugin

### ISSUE THREAD

**Issue by noproxy** [Ottermandias/Glamourer#41]
```
2022-06-28 15:40:46.470 +08:00 [ERR] [LOCALPLUGIN] Error while loading Glamourer
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Glamourer.Customization.CustomizationOptions.GetFaces(CharaMakeParams row)
   at Glamourer.Customization.CustomizationOptions.GetSet(SubRace race, Gender gender)
   at Glamourer.Customization.CustomizationOptions..ctor(DalamudPluginInterface pi, DataManager gameData, ClientLanguage language)
   at Glamourer.Customization.CustomizationManager.Create(DalamudPluginInterface pi, DataManager gameData, ClientLanguage language)
   at Glamourer.Glamourer..ctor(DalamudPluginInterface pluginInterface)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects) in D:\a\Dalamud\Dalamud\Dalamud\IoC\Internal\ServiceContainer.cs:line 0
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in D:\a\Dalamud\Dalamud\Dalamud\Plugin\Internal\LocalPlugin.cs:line 334
2022-06-28 15:40:46.470 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNi0yOFQxNTo0MDo0Ni40NzAzNDA4KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uTnVsbFJlZmVyZW5jZUV4Y2VwdGlvbjogT2JqZWN0IHJlZmVyZW5jZSBub3Qgc2V0IHRvIGFuIGluc3RhbmNlIG9mIGFuIG9iamVjdC5cclxuICAgYXQgR2xhbW91cmVyLkN1c3RvbWl6YXRpb24uQ3VzdG9taXphdGlvbk9wdGlvbnMuR2V0RmFjZXMoQ2hhcmFNYWtlUGFyYW1zIHJvdylcclxuICAgYXQgR2xhbW91cmVyLkN1c3RvbWl6YXRpb24uQ3VzdG9taXphdGlvbk9wdGlvbnMuR2V0U2V0KFN1YlJhY2UgcmFjZSwgR2VuZGVyIGdlbmRlcilcclxuICAgYXQgR2xhbW91cmVyLkN1c3RvbWl6YXRpb24uQ3VzdG9taXphdGlvbk9wdGlvbnMuLmN0b3IoRGFsYW11ZFBsdWdpbkludGVyZmFjZSBwaSwgRGF0YU1hbmFnZXIgZ2FtZURhdGEsIENsaWVudExhbmd1YWdlIGxhbmd1YWdlKVxyXG4gICBhdCBHbGFtb3VyZXIuQ3VzdG9taXphdGlvbi5DdXN0b21pemF0aW9uTWFuYWdlci5DcmVhdGUoRGFsYW11ZFBsdWdpbkludGVyZmFjZSBwaSwgRGF0YU1hbmFnZXIgZ2FtZURhdGEsIENsaWVudExhbmd1YWdlIGxhbmd1YWdlKVxyXG4gICBhdCBHbGFtb3VyZXIuR2xhbW91cmVyLi5jdG9yKERhbGFtdWRQbHVnaW5JbnRlcmZhY2UgcGx1Z2luSW50ZXJmYWNlKVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlJ1bnRpbWVNZXRob2RIYW5kbGUuSW52b2tlTWV0aG9kKE9iamVjdCB0YXJnZXQsIE9iamVjdFtdIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBjb25zdHJ1Y3RvciwgQm9vbGVhbiB3cmFwRXhjZXB0aW9ucylcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZUNvbnN0cnVjdG9ySW5mby5JbnZva2UoT2JqZWN0IG9iaiwgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIsIEJpbmRlciBiaW5kZXIsIE9iamVjdFtdIHBhcmFtZXRlcnMsIEN1bHR1cmVJbmZvIGN1bHR1cmUpXHJcbiAgIGF0IERhbGFtdWQuSW9DLkludGVybmFsLlNlcnZpY2VDb250YWluZXIuQ3JlYXRlKFR5cGUgb2JqZWN0VHlwZSwgT2JqZWN0W10gc2NvcGVkT2JqZWN0cykgaW4gRDpcXGFcXERhbGFtdWRcXERhbGFtdWRcXERhbGFtdWRcXElvQ1xcSW50ZXJuYWxcXFNlcnZpY2VDb250YWluZXIuY3M6bGluZSAwXHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLkxvY2FsUGx1Z2luLkxvYWQoUGx1Z2luTG9hZFJlYXNvbiByZWFzb24sIEJvb2xlYW4gcmVsb2FkaW5nKSBpbiBEOlxcYVxcRGFsYW11ZFxcRGFsYW11ZFxcRGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcTG9jYWxQbHVnaW4uY3M6bGluZSAzMzQiLCJDb250ZXh0IjoiW0xPQ0FMUExVR0lOXSBFcnJvciB3aGlsZSBsb2FkaW5nIEdsYW1vdXJlciJ9
2022-06-28 15:40:46.471 +08:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
```
It occurs to me every time I install the plugin from the plugin manager. 

Glamourer Version: 0.1.0.2
Dalaumd Version: 6.3.0.13
FFXIV Version: China, 6.05

**Comment by Ottermandias** [comment]
I can not support the chinese client, sorry.
